# Generated by Django 5.2.3 on 2025-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userhealthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentary (little or no exercise)'), ('LIGHT', 'Lightly active (light exercise 1-3 days/week)'), ('MODERATE', 'Moderately active (moderate exercise 3-5 days/week)'), ('ACTIVE', 'Very active (hard exercise 6-7 days/week)'), ('VERY_ACTIVE', 'Super active (very hard exercise/job & exercise 2x/day)')], help_text='Select your typical daily activity level.', max_length=20, null=True),
        ),
    ]
