# Generated by Django 5.2.3 on 2025-06-13 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritioncategory',
            options={'verbose_name_plural': 'Nutrition Categories'},
        ),
        migrations.CreateModel(
            name='MealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(help_text='List each ingredient on a new line.')),
                ('instructions', models.TextField(help_text='Provide step-by-step instructions.')),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes.', null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, help_text='Cooking time in minutes.', null=True)),
                ('servings', models.PositiveIntegerField(blank=True, help_text='Number of servings.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the meal.', null=True, upload_to='meal_recipe_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='nutrition.nutritioncategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meal Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
