# Generated by Django 5.2.3 on 2025-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_nutritioncategory_options_mealrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecipe',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: Link to a recipe video (e.g., YouTube).', null=True),
        ),
    ]
