# Generated by Django 5.2.3 on 2025-06-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutcategory',
            options={'verbose_name_plural': 'Workout Categories'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='representative_image',
            field=models.ImageField(blank=True, help_text='Admin uploaded representative image', null=True, upload_to='exercise_images/'),
        ),
    ]
