# Generated by Django 5.2.3 on 2025-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userhealthdata'),
        ('workouts', '0002_alter_workoutcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_focus',
            field=models.CharField(blank=True, choices=[('UPPER', 'Upper Body'), ('LOWER', 'Lower Body'), ('FULL', 'Full Body'), ('CORE', 'Core'), ('OTHER', 'Other')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='contraindicated_for_diseases',
            field=models.ManyToManyField(blank=True, help_text='Select diseases for which this exercise is NOT recommended.', related_name='contraindicated_exercises', to='users.disease'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_home_friendly',
            field=models.BooleanField(default=True, help_text='Can this exercise be typically done at home?'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='workouts.tag'),
        ),
    ]
