# Generated by Django 5.2.3 on 2025-06-13 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_tag_exercise_body_focus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(blank=True, help_text='Upload an image demonstrating the exercise.', null=True, upload_to='user_exercise_contributions/images/')),
                ('uploaded_video', models.FileField(blank=True, help_text='Upload a video demonstrating the exercise.', null=True, upload_to='user_exercise_contributions/videos/')),
                ('external_video_url', models.URLField(blank=True, help_text='Or, link to an external video (e.g., YouTube).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any notes or comments about your contribution.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contributions', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Exercise Contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
