# Generated by Django 5.2.3 on 2025-06-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_userexercisecontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='show_on_map',
            field=models.BooleanField(default=False, help_text='Display this muscle group on the interactive map.'),
        ),
    ]
